// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("AdjustedPriceModels", Schema = "dbo")]
    public class AdjustedPriceModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.AdjustedPriceModels", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"ProductId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Product ID")]
        public int ProductId { get; set; }

        [Column(@"ISIN", Order = 3, TypeName = "nvarchar(max)")]
        [Display(Name = "Isin")]
        public string Isin { get; set; }

        [Column(@"Value", Order = 4, TypeName = "decimal")]
        [Required]
        [Display(Name = "Value")]
        public decimal Value { get; set; }

        [Column(@"Type", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Type")]
        public int Type { get; set; }

        [Column(@"FromDateJalali", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "From date jalali")]
        public string FromDateJalali { get; set; }

        [Column(@"ToDateJalali", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "To date jalali")]
        public string ToDateJalali { get; set; }

        [Column(@"Description", Order = 8, TypeName = "nvarchar(max)")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"Reason", Order = 9, TypeName = "nvarchar(max)")]
        [Display(Name = "Reason")]
        public string Reason { get; set; }

        [Column(@"Created", Order = 10, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created")]
        public System.DateTime Created { get; set; }

        [Column(@"Modified", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Modified")]
        public System.DateTime Modified { get; set; }

        [Column(@"Symbol", Order = 12, TypeName = "nvarchar(max)")]
        [Display(Name = "Symbol")]
        public string Symbol { get; set; }

        [Column(@"ProductTitle", Order = 13, TypeName = "nvarchar(max)")]
        [Display(Name = "Product title")]
        public string ProductTitle { get; set; }

        [Column(@"SecurityExchangeId", Order = 14, TypeName = "int")]
        [Required]
        [Display(Name = "Security exchange ID")]
        public int SecurityExchangeId { get; set; }

        [Column(@"TypeTitle", Order = 15, TypeName = "nvarchar(max)")]
        [Display(Name = "Type title")]
        public string TypeTitle { get; set; }

        [Column(@"IsEditMode", Order = 16, TypeName = "bit")]
        [Required]
        [Display(Name = "Is edit mode")]
        public bool IsEditMode { get; set; }

        [Column(@"SubmitButton", Order = 17, TypeName = "nvarchar(max)")]
        [Display(Name = "Submit button")]
        public string SubmitButton { get; set; }
    }

}
// </auto-generated>
