// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class AdjustedPriceModelMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdjustedPriceModel>
    {
        public AdjustedPriceModelMapper()
            : this("dbo")
        {
        }

        public AdjustedPriceModelMapper(string schema)
        {
            Property(x => x.Isin).IsOptional();
            Property(x => x.Value).HasPrecision(18,2);
            Property(x => x.FromDateJalali).IsOptional();
            Property(x => x.ToDateJalali).IsOptional();
            Property(x => x.Description).IsOptional();
            Property(x => x.Reason).IsOptional();
            Property(x => x.Symbol).IsOptional();
            Property(x => x.ProductTitle).IsOptional();
            Property(x => x.TypeTitle).IsOptional();
            Property(x => x.SubmitButton).IsOptional();
        }
    }

}
// </auto-generated>
