// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("AspNetUsers", Schema = "dbo")]
    public class AspNetUser1
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "nvarchar")]
        [Index(@"PK_dbo.AspNetUsers", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Id")]
        public string Id { get; set; }

        [Column(@"Email", Order = 2, TypeName = "nvarchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Column(@"EmailConfirmed", Order = 3, TypeName = "bit")]
        [Required]
        [Display(Name = "Email confirmed")]
        public bool EmailConfirmed { get; set; }

        [Column(@"PasswordHash", Order = 4, TypeName = "nvarchar(max)")]
        [Display(Name = "Password hash")]
        public string PasswordHash { get; set; }

        [Column(@"SecurityStamp", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Security stamp")]
        public string SecurityStamp { get; set; }

        [Column(@"PhoneNumber", Order = 6, TypeName = "nvarchar(max)")]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        [Column(@"PhoneNumberConfirmed", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Phone number confirmed")]
        public bool PhoneNumberConfirmed { get; set; }

        [Column(@"TwoFactorEnabled", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Two factor enabled")]
        public bool TwoFactorEnabled { get; set; }

        [Column(@"LockoutEndDateUtc", Order = 9, TypeName = "datetime")]
        [Display(Name = "Lockout end date utc")]
        public System.DateTime? LockoutEndDateUtc { get; set; }

        [Column(@"LockoutEnabled", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Lockout enabled")]
        public bool LockoutEnabled { get; set; }

        [Column(@"AccessFailedCount", Order = 11, TypeName = "int")]
        [Required]
        [Display(Name = "Access failed count")]
        public int AccessFailedCount { get; set; }

        [Column(@"UserName", Order = 12, TypeName = "nvarchar")]
        [Index(@"UserNameIndex", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(256)]
        [StringLength(256)]
        [DataType(DataType.Text)]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public virtual System.Collections.Generic.ICollection<AspNetRole1> AspNetRole1 { get; set; }
        public virtual System.Collections.Generic.ICollection<AspNetUserClaim1> AspNetUserClaim1 { get; set; }
        public virtual System.Collections.Generic.ICollection<AspNetUserLogin1> AspNetUserLogin1 { get; set; }

        public AspNetUser1()
        {
            AspNetUserClaim1 = new System.Collections.Generic.List<AspNetUserClaim1>();
            AspNetUserLogin1 = new System.Collections.Generic.List<AspNetUserLogin1>();
            AspNetRole1 = new System.Collections.Generic.List<AspNetRole1>();
        }
    }

}
// </auto-generated>
