// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("AspNetUsers", Schema = "sec")]
    public class AspNetUser
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "nvarchar")]
        [Index(@"PK_dbo.AspNetUsers", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Id")]
        public string Id { get; set; }

        [Column(@"Hometown", Order = 2, TypeName = "nvarchar(max)")]
        [Display(Name = "Hometown")]
        public string Hometown { get; set; }

        [Column(@"Email", Order = 3, TypeName = "nvarchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Column(@"EmailConfirmed", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Email confirmed")]
        public bool EmailConfirmed { get; set; }

        [Column(@"PasswordHash", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Password hash")]
        public string PasswordHash { get; set; }

        [Column(@"SecurityStamp", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Security stamp")]
        public string SecurityStamp { get; set; }

        [Column(@"PhoneNumber", Order = 7, TypeName = "nvarchar(max)")]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        [Column(@"PhoneNumberConfirmed", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Phone number confirmed")]
        public bool PhoneNumberConfirmed { get; set; }

        [Column(@"TwoFactorEnabled", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Two factor enabled")]
        public bool TwoFactorEnabled { get; set; }

        [Column(@"LockoutEndDateUtc", Order = 10, TypeName = "datetime")]
        [Display(Name = "Lockout end date utc")]
        public System.DateTime? LockoutEndDateUtc { get; set; }

        [Column(@"LockoutEnabled", Order = 11, TypeName = "bit")]
        [Required]
        [Display(Name = "Lockout enabled")]
        public bool LockoutEnabled { get; set; }

        [Column(@"AccessFailedCount", Order = 12, TypeName = "int")]
        [Required]
        [Display(Name = "Access failed count")]
        public int AccessFailedCount { get; set; }

        [Column(@"UserName", Order = 13, TypeName = "nvarchar")]
        [Required]
        [MaxLength(256)]
        [StringLength(256)]
        [DataType(DataType.Text)]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Column(@"DisplayName", Order = 14, TypeName = "nvarchar(max)")]
        [Display(Name = "Display name")]
        public string DisplayName { get; set; }

        [Column(@"CreateDate", Order = 15, TypeName = "datetime")]
        [Display(Name = "Create date")]
        public System.DateTime? CreateDate { get; set; }

        [Column(@"IsAdmin", Order = 16, TypeName = "bit")]
        [Required]
        [Display(Name = "Is admin")]
        public bool IsAdmin { get; set; }

        [Column(@"Status", Order = 17, TypeName = "int")]
        [Display(Name = "Status")]
        public int? Status { get; set; }

        [Column(@"IsCustomizedAccess", Order = 18, TypeName = "bit")]
        [Required]
        [Display(Name = "Is customized access")]
        public bool IsCustomizedAccess { get; set; }

        public virtual System.Collections.Generic.ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual System.Collections.Generic.ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual System.Collections.Generic.ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }

        public AspNetUser()
        {
            AspNetUserClaims = new System.Collections.Generic.List<AspNetUserClaim>();
            AspNetUserLogins = new System.Collections.Generic.List<AspNetUserLogin>();
            AspNetRoles = new System.Collections.Generic.List<AspNetRole>();
        }
    }

}
// </auto-generated>
