// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("ClientClaims", Schema = "sec")]
    public class ClientClaim
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ClientClaims", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"Type", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Type")]
        public string Type { get; set; }

        [Column(@"Value", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Value")]
        public string Value { get; set; }

        [Column(@"Client_Id", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Client ID")]
        public int ClientId { get; set; }


        [ForeignKey("ClientId")] public virtual Client Client { get; set; }
    }

}
// </auto-generated>
