// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class ClientRedirectUriMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClientRedirectUri>
    {
        public ClientRedirectUriMapper()
            : this("sec")
        {
        }

        public ClientRedirectUriMapper(string schema)
        {

        }
    }

}
// </auto-generated>
