// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("ClientSecrets", Schema = "sec")]
    public class ClientSecret
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ClientSecrets", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"Value", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Value")]
        public string Value { get; set; }

        [Column(@"Type", Order = 3, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Type")]
        public string Type { get; set; }

        [Column(@"Description", Order = 4, TypeName = "nvarchar")]
        [MaxLength(2000)]
        [StringLength(2000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"Expiration", Order = 5, TypeName = "datetimeoffset")]
        [Display(Name = "Expiration")]
        public System.DateTimeOffset? Expiration { get; set; }

        [Column(@"Client_Id", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Client ID")]
        public int ClientId { get; set; }


        [ForeignKey("ClientId")] public virtual Client Client { get; set; }
    }

}
// </auto-generated>
