// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("Documents", Schema = "dbo")]
    public class Document
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_Documents", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"DocType", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Doc type")]
        public int DocType { get; set; }

        [Column(@"DocTitle", Order = 3, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Doc title")]
        public string DocTitle { get; set; }

        [Column(@"binery", Order = 4, TypeName = "varbinary(max)")]
        [Display(Name = "Binery")]
        public byte[] Binery { get; set; }

        [Column(@"Created", Order = 5, TypeName = "datetime")]
        [Display(Name = "Created")]
        public System.DateTime? Created { get; set; }

        [Column(@"Modified", Order = 6, TypeName = "datetime")]
        [Display(Name = "Modified")]
        public System.DateTime? Modified { get; set; }

        [Column(@"PartyId", Order = 7, TypeName = "int")]
        [Display(Name = "Party ID")]
        public int? PartyId { get; set; }

        [Column(@"UserId", Order = 8, TypeName = "nvarchar")]
        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "User ID")]
        public string UserId { get; set; }

        [Column(@"ModifiedBy", Order = 9, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; }

        [Column(@"CreatedBy", Order = 10, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"Size", Order = 11, TypeName = "int")]
        [Display(Name = "Size")]
        public int? Size { get; set; }

        [Column(@"Extention", Order = 12, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Extention")]
        public string Extention { get; set; }


        [ForeignKey("PartyId")] public RetailParty RetailParty { get; set; }
    }

}
// </auto-generated>
