// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class DocumentMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Document>
    {
        public DocumentMapper()
            : this("dbo")
        {
        }

        public DocumentMapper(string schema)
        {
            Property(x => x.DocTitle).IsOptional().IsFixedLength();
            Property(x => x.Binery).IsOptional();
            Property(x => x.Created).IsOptional();
            Property(x => x.Modified).IsOptional();
            Property(x => x.PartyId).IsOptional();
            Property(x => x.UserId).IsOptional();
            Property(x => x.ModifiedBy).IsOptional();
            Property(x => x.CreatedBy).IsOptional();

        }
    }

}
// </auto-generated>
