// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public interface IIranMarketerContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AcademicField> AcademicFields { get; set; }
        System.Data.Entity.DbSet<AdjustedPriceModel> AdjustedPriceModels { get; set; }
        System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; }
        System.Data.Entity.DbSet<AspNetRole1> AspNetRole1 { get; set; }
        System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; }
        System.Data.Entity.DbSet<AspNetUser1> AspNetUser1 { get; set; }
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        System.Data.Entity.DbSet<AspNetUserClaim1> AspNetUserClaim1 { get; set; }
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        System.Data.Entity.DbSet<AspNetUserLogin1> AspNetUserLogin1 { get; set; }
        System.Data.Entity.DbSet<Client> Clients { get; set; }
        System.Data.Entity.DbSet<ClientClaim> ClientClaims { get; set; }
        System.Data.Entity.DbSet<ClientCorsOrigin> ClientCorsOrigins { get; set; }
        System.Data.Entity.DbSet<ClientCustomGrantType> ClientCustomGrantTypes { get; set; }
        System.Data.Entity.DbSet<ClientIdPRestriction> ClientIdPRestrictions { get; set; }
        System.Data.Entity.DbSet<ClientPostLogoutRedirectUri> ClientPostLogoutRedirectUris { get; set; }
        System.Data.Entity.DbSet<ClientRedirectUri> ClientRedirectUris { get; set; }
        System.Data.Entity.DbSet<ClientScope> ClientScopes { get; set; }
        System.Data.Entity.DbSet<ClientSecret> ClientSecrets { get; set; }
        System.Data.Entity.DbSet<Consent> Consents { get; set; }
        System.Data.Entity.DbSet<Document> Documents { get; set; }
        System.Data.Entity.DbSet<Industry> Industries { get; set; }
        System.Data.Entity.DbSet<JobCategory> JobCategories { get; set; }
        System.Data.Entity.DbSet<JobPrefer> JobPrefers { get; set; }
        System.Data.Entity.DbSet<Log> Logs { get; set; }
        System.Data.Entity.DbSet<PageRepository> PageRepositories { get; set; }
        System.Data.Entity.DbSet<PartyUniversity> PartyUniversities { get; set; }
        System.Data.Entity.DbSet<Region> Regions { get; set; }
        System.Data.Entity.DbSet<RetailParty> RetailParties { get; set; }
        System.Data.Entity.DbSet<Scope> Scopes { get; set; }
        System.Data.Entity.DbSet<ScopeClaim> ScopeClaims { get; set; }
        System.Data.Entity.DbSet<ScopeSecret> ScopeSecrets { get; set; }
        System.Data.Entity.DbSet<WorkExperience> WorkExperiences { get; set; }

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type);
        System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SearchRegionsReturnModel>> SearchRegionsAsync(string filter, int? type);

    }

}
// </auto-generated>
