// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public interface IIranMarketerContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AcademicField> AcademicFields { get; set; }
        System.Data.Entity.DbSet<AdjustedPriceModel> AdjustedPriceModels { get; set; }
        System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; }
        System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; }
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        System.Data.Entity.DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        System.Data.Entity.DbSet<Document> Documents { get; set; }
        System.Data.Entity.DbSet<Industry> Industries { get; set; }
        System.Data.Entity.DbSet<JobCategory> JobCategories { get; set; }
        System.Data.Entity.DbSet<JobPost> JobPosts { get; set; }
        System.Data.Entity.DbSet<JobPrefer> JobPrefers { get; set; }
        System.Data.Entity.DbSet<JobPreferIndustry> JobPreferIndustries { get; set; }
        System.Data.Entity.DbSet<JobPreferJobCategory> JobPreferJobCategories { get; set; }
        System.Data.Entity.DbSet<JobRequest> JobRequests { get; set; }
        System.Data.Entity.DbSet<LegalParty> LegalParties { get; set; }
        System.Data.Entity.DbSet<Log> Logs { get; set; }
        System.Data.Entity.DbSet<PartyUniversity> PartyUniversities { get; set; }
        System.Data.Entity.DbSet<Region> Regions { get; set; }
        System.Data.Entity.DbSet<RetailParty> RetailParties { get; set; }
        System.Data.Entity.DbSet<sec_AspNetRole> sec_AspNetRoles { get; set; }
        System.Data.Entity.DbSet<sec_AspNetUser> sec_AspNetUsers { get; set; }
        System.Data.Entity.DbSet<sec_AspNetUserClaim> sec_AspNetUserClaims { get; set; }
        System.Data.Entity.DbSet<sec_AspNetUserLogin> sec_AspNetUserLogins { get; set; }
        System.Data.Entity.DbSet<sec_AspNetUserRole> sec_AspNetUserRoles { get; set; }
        System.Data.Entity.DbSet<sec_Client> sec_Clients { get; set; }
        System.Data.Entity.DbSet<sec_ClientClaim> sec_ClientClaims { get; set; }
        System.Data.Entity.DbSet<sec_ClientCorsOrigin> sec_ClientCorsOrigins { get; set; }
        System.Data.Entity.DbSet<sec_ClientCustomGrantType> sec_ClientCustomGrantTypes { get; set; }
        System.Data.Entity.DbSet<sec_ClientIdPRestriction> sec_ClientIdPRestrictions { get; set; }
        System.Data.Entity.DbSet<sec_ClientPostLogoutRedirectUri> sec_ClientPostLogoutRedirectUris { get; set; }
        System.Data.Entity.DbSet<sec_ClientRedirectUri> sec_ClientRedirectUris { get; set; }
        System.Data.Entity.DbSet<sec_ClientScope> sec_ClientScopes { get; set; }
        System.Data.Entity.DbSet<sec_ClientSecret> sec_ClientSecrets { get; set; }
        System.Data.Entity.DbSet<sec_Consent> sec_Consents { get; set; }
        System.Data.Entity.DbSet<sec_PageRepository> sec_PageRepositories { get; set; }
        System.Data.Entity.DbSet<sec_Scope> sec_Scopes { get; set; }
        System.Data.Entity.DbSet<sec_ScopeClaim> sec_ScopeClaims { get; set; }
        System.Data.Entity.DbSet<sec_ScopeSecret> sec_ScopeSecrets { get; set; }
        System.Data.Entity.DbSet<WorkExperience> WorkExperiences { get; set; }

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type);
        System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SearchRegionsReturnModel>> SearchRegionsAsync(string filter, int? type);

    }

}
// </auto-generated>
