// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    using System.Linq;

    public class IranMarketerContext : System.Data.Entity.DbContext, IIranMarketerContext
    {
        public System.Data.Entity.DbSet<AcademicField> AcademicFields { get; set; }
        public System.Data.Entity.DbSet<AdjustedPriceModel> AdjustedPriceModels { get; set; }
        public System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; }
        public System.Data.Entity.DbSet<AspNetRole1> AspNetRole1 { get; set; }
        public System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; }
        public System.Data.Entity.DbSet<AspNetUser1> AspNetUser1 { get; set; }
        public System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public System.Data.Entity.DbSet<AspNetUserClaim1> AspNetUserClaim1 { get; set; }
        public System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public System.Data.Entity.DbSet<AspNetUserLogin1> AspNetUserLogin1 { get; set; }
        public System.Data.Entity.DbSet<Client> Clients { get; set; }
        public System.Data.Entity.DbSet<ClientClaim> ClientClaims { get; set; }
        public System.Data.Entity.DbSet<ClientCorsOrigin> ClientCorsOrigins { get; set; }
        public System.Data.Entity.DbSet<ClientCustomGrantType> ClientCustomGrantTypes { get; set; }
        public System.Data.Entity.DbSet<ClientIdPRestriction> ClientIdPRestrictions { get; set; }
        public System.Data.Entity.DbSet<ClientPostLogoutRedirectUri> ClientPostLogoutRedirectUris { get; set; }
        public System.Data.Entity.DbSet<ClientRedirectUri> ClientRedirectUris { get; set; }
        public System.Data.Entity.DbSet<ClientScope> ClientScopes { get; set; }
        public System.Data.Entity.DbSet<ClientSecret> ClientSecrets { get; set; }
        public System.Data.Entity.DbSet<Consent> Consents { get; set; }
        public System.Data.Entity.DbSet<Document> Documents { get; set; }
        public System.Data.Entity.DbSet<Industry> Industries { get; set; }
        public System.Data.Entity.DbSet<JobCategory> JobCategories { get; set; }
        public System.Data.Entity.DbSet<JobPrefer> JobPrefers { get; set; }
        public System.Data.Entity.DbSet<Log> Logs { get; set; }
        public System.Data.Entity.DbSet<PageRepository> PageRepositories { get; set; }
        public System.Data.Entity.DbSet<PartyUniversity> PartyUniversities { get; set; }
        public System.Data.Entity.DbSet<Region> Regions { get; set; }
        public System.Data.Entity.DbSet<RetailParty> RetailParties { get; set; }
        public System.Data.Entity.DbSet<Scope> Scopes { get; set; }
        public System.Data.Entity.DbSet<ScopeClaim> ScopeClaims { get; set; }
        public System.Data.Entity.DbSet<ScopeSecret> ScopeSecrets { get; set; }
        public System.Data.Entity.DbSet<WorkExperience> WorkExperiences { get; set; }

        static IranMarketerContext()
        {
            System.Data.Entity.Database.SetInitializer(new System.Data.Entity.MigrateDatabaseToLatestVersion<IranMarketerContext, IranMarketer2017259>());
        }

        public IranMarketerContext()
            : base("Name=StagingDbContext")
        {
        }

        public IranMarketerContext(string connectionString)
            : base(connectionString)
        {
        }

        public IranMarketerContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public IranMarketerContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public IranMarketerContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AcademicFieldMapper());
            modelBuilder.Configurations.Add(new AdjustedPriceModelMapper());
            modelBuilder.Configurations.Add(new AspNetRoleMapper());
            modelBuilder.Configurations.Add(new AspNetRole1Mapper());
            modelBuilder.Configurations.Add(new AspNetUserMapper());
            modelBuilder.Configurations.Add(new AspNetUser1Mapper());
            modelBuilder.Configurations.Add(new AspNetUserClaimMapper());
            modelBuilder.Configurations.Add(new AspNetUserClaim1Mapper());
            modelBuilder.Configurations.Add(new AspNetUserLoginMapper());
            modelBuilder.Configurations.Add(new AspNetUserLogin1Mapper());
            modelBuilder.Configurations.Add(new ClientMapper());
            modelBuilder.Configurations.Add(new ClientClaimMapper());
            modelBuilder.Configurations.Add(new ClientCorsOriginMapper());
            modelBuilder.Configurations.Add(new ClientCustomGrantTypeMapper());
            modelBuilder.Configurations.Add(new ClientIdPRestrictionMapper());
            modelBuilder.Configurations.Add(new ClientPostLogoutRedirectUriMapper());
            modelBuilder.Configurations.Add(new ClientRedirectUriMapper());
            modelBuilder.Configurations.Add(new ClientScopeMapper());
            modelBuilder.Configurations.Add(new ClientSecretMapper());
            modelBuilder.Configurations.Add(new ConsentMapper());
            modelBuilder.Configurations.Add(new DocumentMapper());
            modelBuilder.Configurations.Add(new IndustryMapper());
            modelBuilder.Configurations.Add(new JobCategoryMapper());
            modelBuilder.Configurations.Add(new JobPreferMapper());
            modelBuilder.Configurations.Add(new LogMapper());
            modelBuilder.Configurations.Add(new PageRepositoryMapper());
            modelBuilder.Configurations.Add(new PartyUniversityMapper());
            modelBuilder.Configurations.Add(new RegionMapper());
            modelBuilder.Configurations.Add(new RetailPartyMapper());
            modelBuilder.Configurations.Add(new ScopeMapper());
            modelBuilder.Configurations.Add(new ScopeClaimMapper());
            modelBuilder.Configurations.Add(new ScopeSecretMapper());
            modelBuilder.Configurations.Add(new WorkExperienceMapper());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AcademicFieldMapper(schema));
            modelBuilder.Configurations.Add(new AdjustedPriceModelMapper(schema));
            modelBuilder.Configurations.Add(new AspNetRoleMapper(schema));
            modelBuilder.Configurations.Add(new AspNetRole1Mapper(schema));
            modelBuilder.Configurations.Add(new AspNetUserMapper(schema));
            modelBuilder.Configurations.Add(new AspNetUser1Mapper(schema));
            modelBuilder.Configurations.Add(new AspNetUserClaimMapper(schema));
            modelBuilder.Configurations.Add(new AspNetUserClaim1Mapper(schema));
            modelBuilder.Configurations.Add(new AspNetUserLoginMapper(schema));
            modelBuilder.Configurations.Add(new AspNetUserLogin1Mapper(schema));
            modelBuilder.Configurations.Add(new ClientMapper(schema));
            modelBuilder.Configurations.Add(new ClientClaimMapper(schema));
            modelBuilder.Configurations.Add(new ClientCorsOriginMapper(schema));
            modelBuilder.Configurations.Add(new ClientCustomGrantTypeMapper(schema));
            modelBuilder.Configurations.Add(new ClientIdPRestrictionMapper(schema));
            modelBuilder.Configurations.Add(new ClientPostLogoutRedirectUriMapper(schema));
            modelBuilder.Configurations.Add(new ClientRedirectUriMapper(schema));
            modelBuilder.Configurations.Add(new ClientScopeMapper(schema));
            modelBuilder.Configurations.Add(new ClientSecretMapper(schema));
            modelBuilder.Configurations.Add(new ConsentMapper(schema));
            modelBuilder.Configurations.Add(new DocumentMapper(schema));
            modelBuilder.Configurations.Add(new IndustryMapper(schema));
            modelBuilder.Configurations.Add(new JobCategoryMapper(schema));
            modelBuilder.Configurations.Add(new JobPreferMapper(schema));
            modelBuilder.Configurations.Add(new LogMapper(schema));
            modelBuilder.Configurations.Add(new PageRepositoryMapper(schema));
            modelBuilder.Configurations.Add(new PartyUniversityMapper(schema));
            modelBuilder.Configurations.Add(new RegionMapper(schema));
            modelBuilder.Configurations.Add(new RetailPartyMapper(schema));
            modelBuilder.Configurations.Add(new ScopeMapper(schema));
            modelBuilder.Configurations.Add(new ScopeClaimMapper(schema));
            modelBuilder.Configurations.Add(new ScopeSecretMapper(schema));
            modelBuilder.Configurations.Add(new WorkExperienceMapper(schema));
            return modelBuilder;
        }

        // Stored Procedures
        public System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type)
        {
            int procResult;
            return SearchRegions(filter, type, out procResult);
        }

        public System.Collections.Generic.List<SearchRegionsReturnModel> SearchRegions(string filter, int? type, out int procResult)
        {
            var filterParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@filter", SqlDbType = System.Data.SqlDbType.NVarChar, Direction = System.Data.ParameterDirection.Input, Value = filter, Size = 100 };
            if (filterParam.Value == null)
                filterParam.Value = System.DBNull.Value;

            var typeParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@type", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Input, Value = type.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!type.HasValue)
                typeParam.Value = System.DBNull.Value;

            var procResultParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@procResult", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output };
            var procResultData = Database.SqlQuery<SearchRegionsReturnModel>("EXEC @procResult = [dbo].[SearchRegions] @filter, @type", filterParam, typeParam, procResultParam).ToList();

            procResult = (int) procResultParam.Value;
            return procResultData;
        }

        public async System.Threading.Tasks.Task<System.Collections.Generic.List<SearchRegionsReturnModel>> SearchRegionsAsync(string filter, int? type)
        {
            var filterParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@filter", SqlDbType = System.Data.SqlDbType.NVarChar, Direction = System.Data.ParameterDirection.Input, Value = filter, Size = 100 };
            if (filterParam.Value == null)
                filterParam.Value = System.DBNull.Value;

            var typeParam = new System.Data.SqlClient.SqlParameter { ParameterName = "@type", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Input, Value = type.GetValueOrDefault(), Precision = 10, Scale = 0 };
            if (!type.HasValue)
                typeParam.Value = System.DBNull.Value;

            var procResultData = await Database.SqlQuery<SearchRegionsReturnModel>("EXEC [dbo].[SearchRegions] @filter, @type", filterParam, typeParam).ToListAsync();

            return procResultData;
        }

    }
}
// </auto-generated>
