// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class JobPreferMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<JobPrefer>
    {
        public JobPreferMapper()
            : this("dbo")
        {
        }

        public JobPreferMapper(string schema)
        {
            Property(x => x.ExpectedSalary).IsOptional();
            Property(x => x.BusinessTrips).IsOptional();
            Property(x => x.Relocate).IsOptional();
            Property(x => x.Created).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.Modified).IsOptional();
            Property(x => x.ModifiedBy).IsOptional().IsFixedLength();

        }
    }

}
// </auto-generated>
