// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class LogMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Log>
    {
        public LogMapper()
            : this("dbo")
        {
        }

        public LogMapper(string schema)
        {
            Property(x => x.ErrorSource).IsOptional();
            Property(x => x.ErrorClass).IsOptional();
            Property(x => x.ErrorMethod).IsOptional();
            Property(x => x.InnerErrorMessage).IsOptional();
        }
    }

}
// </auto-generated>
