// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class PageRepositoryMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PageRepository>
    {
        public PageRepositoryMapper()
            : this("sec")
        {
        }

        public PageRepositoryMapper(string schema)
        {
            Property(x => x.ServiceRepositoryId).IsOptional();
            Property(x => x.PageType).IsOptional();
        }
    }

}
// </auto-generated>
