// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class PartyUniversityMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PartyUniversity>
    {
        public PartyUniversityMapper()
            : this("dbo")
        {
        }

        public PartyUniversityMapper(string schema)
        {
            Property(x => x.DegreeLevel).IsOptional();
            Property(x => x.University).IsOptional();
            Property(x => x.CountryId).IsOptional();
            Property(x => x.CityId).IsOptional();
            Property(x => x.FromDate).IsOptional();
            Property(x => x.ToDate).IsOptional();
            Property(x => x.Average).IsOptional().HasPrecision(2,2);
            Property(x => x.Created).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.Modified).IsOptional();
            Property(x => x.ModifiedBy).IsOptional();

        }
    }

}
// </auto-generated>
