// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class RegionMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Region>
    {
        public RegionMapper()
            : this("dbo")
        {
        }

        public RegionMapper(string schema)
        {
            Property(x => x.Title).IsOptional();
            Property(x => x.EnTitle).IsOptional();
            Property(x => x.CodeId).IsOptional();
            Property(x => x.RegionType).IsOptional();
            Property(x => x.ZipCode).IsOptional();
            Property(x => x.ValidFrom).IsOptional();
            Property(x => x.ValidUntil).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.ModifiedBy).IsOptional();
        }
    }

}
// </auto-generated>
