// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class RetailPartyMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RetailParty>
    {
        public RetailPartyMapper()
            : this("dbo")
        {
        }

        public RetailPartyMapper(string schema)
        {
            Property(x => x.Name).IsOptional();
            Property(x => x.EnName).IsOptional();
            Property(x => x.FirstName).IsOptional();
            Property(x => x.EnFirstName).IsOptional();
            Property(x => x.LastName).IsOptional();
            Property(x => x.EnLastName).IsOptional();
            Property(x => x.FatherName).IsOptional();
            Property(x => x.EnFatherName).IsOptional();
            Property(x => x.NationalId).IsOptional();
            Property(x => x.NationalityPlaceId).IsOptional();
            Property(x => x.CityId).IsOptional();
            Property(x => x.FullName).IsOptional();
            Property(x => x.Address).IsOptional();
            Property(x => x.PhoneNumber).IsOptional();
            Property(x => x.MobileNumber).IsOptional();
            Property(x => x.BirthDate).IsOptional();
            Property(x => x.BirthPlace).IsOptional();
            Property(x => x.Gender).IsOptional();
            Property(x => x.MilitaryServiceStatus).IsOptional();
            Property(x => x.MaritalStatus).IsOptional();
            Property(x => x.ValidFrom).IsOptional();
            Property(x => x.ValidUntil).IsOptional();
            Property(x => x.Modified).IsOptional();
            Property(x => x.Created).IsOptional();
            Property(x => x.ModifiedBy).IsOptional();
            Property(x => x.CreatedBy).IsOptional();

        }
    }

}
// </auto-generated>
