// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("ScopeClaims", Schema = "sec")]
    public class ScopeClaim
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ScopeClaims", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Column(@"Description", Order = 3, TypeName = "nvarchar")]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"AlwaysIncludeInIdToken", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Always include in ID token")]
        public bool AlwaysIncludeInIdToken { get; set; }

        [Column(@"Scope_Id", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Scope ID")]
        public int ScopeId { get; set; }


        [ForeignKey("ScopeId")] public virtual Scope Scope { get; set; }
    }

}
// </auto-generated>
