// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("ScopeSecrets", Schema = "sec")]
    public class ScopeSecret
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ScopeSecrets", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"Description", Order = 2, TypeName = "nvarchar")]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"Expiration", Order = 3, TypeName = "datetimeoffset")]
        [Display(Name = "Expiration")]
        public System.DateTimeOffset? Expiration { get; set; }

        [Column(@"Type", Order = 4, TypeName = "nvarchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Type")]
        public string Type { get; set; }

        [Column(@"Value", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Value")]
        public string Value { get; set; }

        [Column(@"Scope_Id", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Scope ID")]
        public int ScopeId { get; set; }


        [ForeignKey("ScopeId")] public virtual Scope Scope { get; set; }
    }

}
// </auto-generated>
