// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    [Table("WorkExperience", Schema = "dbo")]
    public class WorkExperience
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_WorkExperience", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Column(@"PartyId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Party ID")]
        public int PartyId { get; set; }

        [Column(@"JobTitle", Order = 3, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Job title")]
        public string JobTitle { get; set; }

        [Column(@"JobCategoryId", Order = 4, TypeName = "int")]
        [Display(Name = "Job category ID")]
        public int? JobCategoryId { get; set; }

        [Column(@"CompanyName", Order = 5, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Company name")]
        public string CompanyName { get; set; }

        [Column(@"IndustryId", Order = 6, TypeName = "int")]
        [Display(Name = "Industry ID")]
        public int? IndustryId { get; set; }

        [Column(@"CountryId", Order = 7, TypeName = "int")]
        [Display(Name = "Country ID")]
        public int? CountryId { get; set; }

        [Column(@"CityId", Order = 8, TypeName = "int")]
        [Display(Name = "City ID")]
        public int? CityId { get; set; }

        [Column(@"FromDate", Order = 9, TypeName = "datetime")]
        [Display(Name = "From date")]
        public System.DateTime? FromDate { get; set; }

        [Column(@"ToDate", Order = 10, TypeName = "datetime")]
        [Display(Name = "To date")]
        public System.DateTime? ToDate { get; set; }

        [Column(@"Achievements", Order = 11, TypeName = "nvarchar(max)")]
        [Display(Name = "Achievements")]
        public string Achievements { get; set; }

        [Column(@"StillInThisWork", Order = 12, TypeName = "bit")]
        [Display(Name = "Still in this work")]
        public bool? StillInThisWork { get; set; }


        [ForeignKey("CityId")] public virtual Region Region { get; set; }

        [ForeignKey("IndustryId")] public virtual Industry Industry { get; set; }

        [ForeignKey("JobCategoryId")] public virtual JobCategory JobCategory { get; set; }

        [ForeignKey("PartyId")] public virtual RetailParty RetailParty { get; set; }
    }

}
// </auto-generated>
