// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class WorkExperienceMapper : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkExperience>
    {
        public WorkExperienceMapper()
            : this("dbo")
        {
        }

        public WorkExperienceMapper(string schema)
        {
            Property(x => x.JobTitle).IsOptional();
            Property(x => x.JobCategoryId).IsOptional();
            Property(x => x.CompanyName).IsOptional();
            Property(x => x.IndustryId).IsOptional();
            Property(x => x.CountryId).IsOptional();
            Property(x => x.CityId).IsOptional();
            Property(x => x.FromDate).IsOptional();
            Property(x => x.ToDate).IsOptional();
            Property(x => x.Achievements).IsOptional();
            Property(x => x.StillInThisWork).IsOptional();

        }
    }

}
// </auto-generated>
