// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using Pikad.Framework.Repository;

namespace IranMarketer.Domain.Entity
{

    // JobPrefer
    [Table("JobPrefer", Schema = "dbo")]
    public class JobPrefer : Entity<int>
    {

        [Column(@"ExpectedSalary", Order = 2, TypeName = "int")]
        [Display(Name = "Expected salary")]
        public int? ExpectedSalary { get; set; }

        [Column(@"BusinessTrips", Order = 3, TypeName = "int")]
        [Display(Name = "Business trips")]
        public int? BusinessTrips { get; set; }

        [Column(@"Relocate", Order = 4, TypeName = "int")]
        [Display(Name = "Relocate")]
        public int? Relocate { get; set; }

        [Column(@"PartyId", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Party ID")]
        public int PartyId { get; set; }

        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<Industry> Industries { get; set; }
        [JsonIgnore]

        public virtual System.Collections.Generic.ICollection<JobCategory> JobCategories { get; set; }

       [JsonIgnore]
        [ForeignKey("PartyId")] public virtual RetailParty RetailParty { get; set; }

        public JobPrefer()
        {
            JobCategories = new System.Collections.Generic.List<JobCategory>();
            Industries = new System.Collections.Generic.List<Industry>();
        }
    }

    [Table("JobPreferIndustry",Schema = "dbo")]
    public class JobPreferIndustry
    {
        public int JobPreferId { get; set; }
        public int IndustryId { get; set; }
    }

    [Table("JobPreferJobCategory", Schema = "dbo")]
    public class JobPreferJobCategory
    {
        public int JobPreferId { get; set; }
        public int jobCategoryId { get; set; }
    }
}
// </auto-generated>
