// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IranMarketer.Domain.Entity
{

    public class SearchRegionsReturnModel
    {
        public System.Int32? Id { get; set; }
        public System.String Title { get; set; }
        public System.String EnTitle { get; set; }
        public System.String CodeId { get; set; }
        public System.Int32? RegionType { get; set; }
        public System.String ZipCode { get; set; }
        public System.DateTime? ValidFrom { get; set; }
        public System.DateTime? ValidUntil { get; set; }
      //  public System.DateTime Created { get; set; }
       // public System.DateTime Modified { get; set; }
        public System.String CreatedBy { get; set; }
        public System.String ModifiedBy { get; set; }
    }

}
// </auto-generated>
