// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IranMarketer.Domain.Entity;
using Newtonsoft.Json;
using Pikad.Framework.Repository;

namespace IranMarketer.Domain.DTO
{

    public class WorkExperience : BaseDto<int>
    {
        public string JobTitle { get; set; }

        public int? JobCategoryId { get; set; }

        public string CompanyName { get; set; }

        public int? IndustryId { get; set; }

        public int? CountryId { get; set; }

        public int JobCityId { get; set; }

        public string FromDate { get; set; }

        public string ToDate { get; set; }

        public string Achievements { get; set; }

        public bool? StillInThisWork { get; set; }


        public virtual Region Region { get; set; }

        public virtual Industry Industry { get; set; }


        public virtual JobCategory JobCategory { get; set; }

        public virtual RetailParty RetailParty { get; set; }

        public WorkExperience()
        {
            Region=new Region();
        }
    }

}
// </auto-generated>
